name: Minecraft Mod Build

on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 1.8
          distribution: 'adopt'

      - name: Build Mod with Gradle
        run: ./gradlew build
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0  # Replace with the tag name for the release
          release_name: Release v1.0.0  # Replace with the name of the release
          body: |
            First release !
          draft: false
          prerelease: false